version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda,dynamodb
      - DEFAULT_REGION=us-east-1
      - LAMBDA_DOCKER_NETWORK=my_network
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1  # Enable verbose logging
    volumes:
      - "./init-resources.yaml:/etc/localstack/init/ready.d/init-resources.yaml"  # ready hook
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./lambda:/lambda-code"
    
    networks:
      - my_network
    
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

networks:
  my_network: